# Same dictionary interface used by adm-sbi/G19_v3/nn_rv1.
# Only the eight models used in the manuscript are retained.

model_infos = {
    "aDDM_1": {"disp_mname":"DDM-NoAtt","mul_model":1,"free_pnames":["d","a"],"free_pnames_ml":["d","a"],"free_pranges":[(0.1,5),(1,5)],"free_pranges_ml":[(0.1,5),(1,5)],"fixed_pnames":["theta","lam","s","ndt","gamma","var_v","b0_cslope","d_cslope","std_cslope","ov_cslope"],"fixed_pvalues":[1,-1,1,0,0,0,0,0,0,0],"pnames_disp":["d","a"]},
    "aDDM_2": {"disp_mname":"DDM-AttOnly","mul_model":1,"free_pnames":["d","a"],"free_pnames_ml":["d","a"],"free_pranges":[(0.1,5),(1,5)],"free_pranges_ml":[(0.1,5),(1,5)],"fixed_pnames":["theta","lam","s","ndt","gamma","var_v","b0_cslope","d_cslope","std_cslope","ov_cslope"],"fixed_pvalues":[0,-1,1,0,0,0,0,0,0,0],"pnames_disp":["d","a"]},
    "aDDM_t": {"disp_mname":"DDM-Mul","mul_model":1,"free_pnames":["d","a","theta"],"free_pnames_ml":["d","a","theta"],"free_pranges":[(0.1,5),(1,5),(0.1,1)],"free_pranges_ml":[(0.1,5),(1,5),(0.1,1)],"fixed_pnames":["lam","s","ndt","gamma","var_v","b0_cslope","d_cslope","std_cslope","ov_cslope"],"fixed_pvalues":[-1,1,0,0,0,0,0,0,0],"pnames_disp":["d","a","theta"]},
    "aDDM_g": {"disp_mname":"DDM-Add","mul_model":0,"free_pnames":["d","a","gamma"],"free_pnames_ml":["d","a","gamma"],"free_pranges":[(0.1,5),(1,5),(0.0,1)],"free_pranges_ml":[(0.1,5),(1,5),(0.0,1)],"fixed_pnames":["lam","s","ndt","theta","var_v","b0_cslope","d_cslope","std_cslope","ov_cslope"],"fixed_pvalues":[-1,1,0,1,0,0,0,0,0],"pnames_disp":["d","a","gamma"]},
    "aRACE_1": {"disp_mname":"ACC-NoAtt","mul_model":1,"free_pnames":["d","a"],"free_pnames_ml":["d","a"],"free_pranges":[(0.1,8),(0.5,5)],"free_pranges_ml":[(0.1,8),(0.5,5)],"fixed_pnames":["theta","lam","s","ndt","b","gamma","var_v","b0_cslope","d_cslope","std_cslope","ov_cslope"],"fixed_pvalues":[1,-1,1,0,0,0,0,0,0,0,0],"pnames_disp":["d","a"]},
    "aRACE_2": {"disp_mname":"ACC-AttOnly","mul_model":1,"free_pnames":["d","a"],"free_pnames_ml":["d","a"],"free_pranges":[(0.1,8),(0.5,5)],"free_pranges_ml":[(0.1,8),(0.5,5)],"fixed_pnames":["theta","lam","s","ndt","b","gamma","var_v","b0_cslope","d_cslope","std_cslope","ov_cslope"],"fixed_pvalues":[0,-1,1,0,0,0,0,0,0,0,0],"pnames_disp":["d","a"]},
    "aRACE_t": {"disp_mname":"ACC-Mul","mul_model":1,"free_pnames":["d","a","theta"],"free_pnames_ml":["d","a","theta"],"free_pranges":[(0.1,8),(0.5,5),(0.1,1)],"free_pranges_ml":[(0.1,8),(0.5,5),(0.1,1)],"fixed_pnames":["lam","s","ndt","b","gamma","var_v","b0_cslope","d_cslope","std_cslope","ov_cslope"],"fixed_pvalues":[-1,1,0,0,0,0,0,0,0,0],"pnames_disp":["d","a","theta"]},
    "aRACE_g": {"disp_mname":"ACC-Add","mul_model":0,"free_pnames":["d","a","gamma"],"free_pnames_ml":["d","a","gamma"],"free_pranges":[(0.1,8),(0.5,5),(0.1,1)],"free_pranges_ml":[(0.1,8),(0.5,5),(0.1,1)],"fixed_pnames":["lam","s","ndt","b","theta","var_v","b0_cslope","d_cslope","std_cslope","ov_cslope"],"fixed_pvalues":[-1,1,0,0,1,0,0,0,0,0],"pnames_disp":["d","a","gamma"]},
}
model_names = list(model_infos.keys())
